name: "AI Codegenit"
description: "Run AI check"
author: "madhavi-opsera"
branding:
  icon: "zap"
  color: "purple"

runs:
  using: "composite"
  steps:
    - name: Authenticate to AWS via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::791544005398:role/mcp-github-role
        aws-region: us-east-1
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1| docker login \
          --username AWS \
          --password-stdin 791544005398.dkr.ecr.us-east-1.amazonaws.com/mcp-codeglide
    - name: Run AI App
      shell: bash
      run: |
        mkdir -p input_temp generated_output
        echo "✅ Running container..."
        docker pull 791544005398.dkr.ecr.us-east-1.amazonaws.com/mcp-codeglide:latest
        docker run --rm \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_ACTOR="${{ github.actor }}" \
          -v "${{ github.workspace }}/input:/app/input" \
          -v "${{ github.workspace }}/generated_output:/app/output" \
          791544005398.dkr.ecr.us-east-1.amazonaws.com/mcp-codeglide:latest

    - name: Upload Generated Output
      uses: actions/upload-artifact@v4
      with:
        name: generated_output
        path: generated_output/
