name: "AI Codegenit"
description: "Run AI check"
author: "madhavi-opsera"
branding:
  icon: "zap"
  color: "purple"

runs:
  using: "composite"
  steps:
    - name: Run AI App
      shell: bash
      run: |
        mkdir generated_output
        echo "✅ Running container..."
        docker run --rm \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_ACTOR="${{ github.actor }}" \
          -v "${{ github.workspace }}/input:/app/input" \
          -v "${{ github.workspace }}/generated_output:/app/output" \
          ghcr.io/madhavi-opsera/aicoder:2.0

    - name: Upload Generated Output
      uses: actions/upload-artifact@v4
      with:
        name: generated_output
        path: generated_output/
