name: "Snap Gen"
description: "Run snapgen to create MCP server for APIs. Input dir contains API source code."
branding:
  icon: "chevron-right"
  color: "purple"

inputs:
  input_directory:
    description: 'Input directory containing API source code (relative to workspace). Defaults to project root.'
    required: false
    default: '.'
  create_pr:
    description: 'Create PR with generated code instead of uploading as artifact'
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Run Codeglide MCP gen
      shell: bash
      run: |
        mkdir -p "generated-mcp"
        echo "Running container..."
        
        # Handle directory mounting (defaults to project root)
        if [[ "${{ inputs.input_directory }}" == "." ]] || [[ -z "${{ inputs.input_directory }}" ]]; then
          INPUT_PATH="${{ github.workspace }}"
        else
          INPUT_PATH="${{ github.workspace }}/${{ inputs.input_directory }}"
        fi
        
        docker run --rm \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_ACTOR="${{ github.actor }}" \
          -e GITHUB_ACTIONS=$GITHUB_ACTIONS \
          -v "$INPUT_PATH:/app/input" \
          -v "${{ github.workspace }}/generated-mcp:/app/output" \
          ghcr.io/codeglide/mcpgen:latest

    - name: Create PR
      if: ${{ inputs.create_pr }}
      shell: bash
      run: |
        # Configure git with GitHub Actions identity
        git config --global user.name "snapgn-github-actions[bot]"
        git config --global user.email "snapgn-github-actions[bot]@users.noreply.github.com"

        # Create new branch
        BRANCH_NAME="feat/mcp-server-update/$(date +%Y-%m-%d)--$(date +%H-%M-%S)"
        git checkout -b $BRANCH_NAME
        
        # Create MCP directory if it doesn't exist
        mkdir -p MCP/MCPServer
        
        # Copy generated files
        cp -r generated-mcp/* MCP/MCPServer/
        
        # Commit and push
        git add MCP/MCPServer
        git commit -m "feat: snapgn Auto-generated MCP server code

        Triggered by: @${{ github.actor }}"
        git push origin $BRANCH_NAME

        echo "Branch: $BRANCH_NAME created and pushed successfully!"
        
        echo "To create a PR, visit:"
        echo "https://github.com/${{ github.repository }}/compare/main...$BRANCH_NAME"

    - name: Upload MCP Server
      if: ${{ !inputs.create_pr }}
      uses: actions/upload-artifact@v4
      with:
        name: generated-mcp
        path: generated-mcp/ 
